name: Continuous Integration

on:
  push:
    branches:
      - main             # Acionar no push da branch main
      - "feature/**"     # Acionar no push de qualquer branch que comece com 'feature/'

jobs:
  job1-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Imprimir mensagem
        run: echo "Olá, Mundo"

  job2-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Substitua pela versão correta se necessário

      - name: Step 1 - Sequência de instruções
        run: |
          echo "Uma nova instrução"
          ls            

      - name: Step 2 - Imprimir mensagem
        run: echo "Até logo!"
